const products = [
    {
        "id": 1,
        "category": "over-ear",
        "name": "Sony WH-1000XM4",
        "price": 11990,
        "color": "ivory",
        "images": ["assets/over-ear/wh-1000xm4/image-1.webp", "assets/over-ear/wh-1000xm4/image-2.webp", "assets/over-ear/wh-1000xm4/image-3.webp"],
        "features": ["noise-cancelling", "ambient-sound", "bluetooth"],
        "description-title": "ONLY MUSIC. NOTHING ELSE.",
        "description-text": "It’s just you and your music with the WH-1000XM4 headphones. The easy way to enjoy less noise and even purer sound, with smart listening technology that automatically personalises your experience.",
        "overall-rating": 3.3,
        "rating": [5, 4, 2],
        "reviewer": ["Lem", "Bora8008", "Wakal"],
        "reviews": ["I would rate these 5/5, I purchased them to replace an old pair of ATH-SR6BT, which were metal and super durable. These are also very durable. I travel often and want to listen to my music while I wait on flights; they also stay on my head while working out on the elliptical no issues of them falling off. The sound is excellent. I don't have any disconnect issues. I did notice that if you sync the headphones to multiple products without unsyncing them. Example: I have it sync'd to my iPad and iPhone, if I walk near my iPad it interrupts the music and connects. I would suggest disconnecting so you don't run into that issue. Overall, they are durable and have great sound. I would buy them again.",
            "Great sound and reliable Bluetooth connection.Only downside for me, is that I often touch the other controls by accident, when trying to find the volume controls.", 
            "Everything about the headphones are great EXCEPT for the construction. It has a very common issue of a flimsy plastic part within the hinge breaking causing the headphones to no longer sit flush with the head. I got this product a little under two years ago and it has broken the same way twice. I got it replaced under warranty, but I also had a pair of ATH M50-X that I got ten years ago that broke in exactly the same way. It has broken three times the same way. They are great headphones, but they will break on you, no question."],
    },
    {
        "id": 2,
        "category": "over-ear",
        "name": "Sony ULT WEAR",
        "price": 6990,
        "color": "white",
        "images": ["assets/over-ear/ult-wear/image-1.webp", "assets/over-ear/ult-wear/image-2.webp", "assets/over-ear/ult-wear/image-3.webp"],
        "features": ["noise-cancelling", "ambient-sound", "bluetooth"],
        "description-title": "POWERFUL SOUND. MAKE IT YOUR OWN.",
        "description-text": "With exceptional bass and improved Noise Cancelling, our new ULT WEAR headphones let you bring your favourite festival or club feel with you, everywhere you go.",
        "overall-rating": 4.6,
        "rating": [5, 1, 5],
        "reviewer": ["Happyman0611", "Rhys95", "Syiraa"],
        "reviews": ["With exceptional bass and improved Noise Cancelling, our new ULT WEAR headphones let you bring your favourite festival or club feel with you, everywhere you go.",
            "Bought less than 3 months ago and the right headphone snapped off the headband. All I did was pick it up to put it on. Luckily Sony's warranty doesn't cover physical damage, so I have to pay for repair. Won't be repairing it though. I don't want to go through the same issue again in another 3 months. £180 down the drain.", 
            "Scoured alot of brands and devices for my next headphones, and stumbled upon this one. Great bass, ANC, and just good for me! I fell in love with it and I'm never disappointed with Sony products. It's just right for me!"],
    },
    {
        "id": 3,
        "category": "over-ear",
        "name": "Skullcandy Crucher ANC 2",
        "price": 8990,
        "color": "white",
        "images": ["assets/over-ear/crusher-anc-2/image-1.webp", "assets/over-ear/crusher-anc-2/image-2.webp", "assets/over-ear/crusher-anc-2/image-3.webp"],
        "features": ["noise-cancelling", "ambient-sound", "bluetooth"],
        "description-title": "UNBEATABLE BASS, NOISE CANCELING.",
        "description-text": "Crusher ANC 2 is the headphone with absolutely everything — Personal Sound and hands-free voice control plus a blend of adjustable 4-mic digital active noise canceling and Crusher Bass that is so perfect, we had it patented. Experience full sound and amazing bass you can actually feel.",
        "overall-rating": 4.6,
        "rating": [5, 5, 4],
        "reviewer": ["Hugo", "Cedric", "Koen"],
        "reviews": ["The Crusher ANC 2 is and will be the best headphones i have had. These headphones are AMAZING. The bass is insanely great and therefore i cannot listen to anyone else's headphones ever again. This thing is like a drug. Because if u have had it for about a month it becomes insanely hard to listen to other peoples music without missing the bass. Thank you Skullcandy for making these headphones.",
            "They are absolutely perfect. I love the bass and the sound",
            "Good quality, Good anc, very good sound and bass, sometimes it can be a little fragile it is the second pair i bought because the other one was cracked everywhere because it fell too many times. It is pretty durable tho."],
    },
    {
        "id": 4,
        "category": "over-ear",
        "name": "Skullcandy Hesh ANC",
        "price": 6990,
        "color": "black",
        "images": ["assets/over-ear/hesh-anc/image-1.webp", "assets/over-ear/hesh-anc/image-2.webp", "assets/over-ear/hesh-anc/image-3.webp"],
        "features": ["noise-cancelling", "ambient-sound", "bluetooth"],
        "description-title": "WIRELESS SIMPLICITY WITH NOISE CANCELING.",
        "description-text": "Plenty of people drop a lot of coin to flex that they can afford noise-canceling headphones. Hesh ANC is for the rest of us. For those of us more concerned with sharing a great playlist than showing off our status. But do not think you are compromising: Hesh ANC delivers a 4-mic, digital active noise canceling experience that rivals anything out there.",
        "overall-rating": 4.7,
        "rating": [5, 4, 5],
        "reviewer": ["Stathis", "Beniczki", "Anne"],
        "reviews": ["Active noice cancellation works flawless. Perfect ears fit. Sound is clear.",
            "This headset is fire! Thought the anc would block out more noise, but the sound quality is amazing. Big fan.",
            "Great headphones! Beautiful sound, good noise cancelling. I’m very happy with them."],
    },
    {
        "id": 5,
        "category": "over-ear",
        "name": "Bose QuietComfort",
        "price": 11990,
        "color": "ivory",
        "images": ["assets/over-ear/quietcomfort/image-1.webp", "assets/over-ear/quietcomfort/image-2.webp", "assets/over-ear/quietcomfort/image-3.webp"],
        "features": ["noise-cancelling", "ambient-sound", "bluetooth"],
        "description-title": "TAKE OVER THE TEMPO.",
        "description-text": "Take charge of your music and stride along to the beat. High-fidelity audio and legendary noise cancellation work their magic by sealing you in, eliminating distractions, and letting you dive deep into your own rhythm. Toggle between Quiet and Aware Modes, or create a Custom Mode and adjust outside sound to the moment. The design is iconic and the comfort lasting, while an optional audio cable with an in-line microphone plugs you into sound as bold as you, even without a Bluetooth® connection.",
        "overall-rating": 4.5,
        "rating": [5, 4, 3],
        "reviewer": ["RKG", "Nad", "Max768"],
        "reviews": ["Great pair of headphones. Very stylish yet very comfortable. Lightweight too. The only drawback would be that you cannot turn the noise cancelling off unlike its predecessor QC 35ii's. Overall, a really decent pair of headphones.",
            "Happy with it, except for the tiny functional buttons of the right ear cup.",
            "I bougth this back in 2022 and the sound in the right ear usually stops working at some point. I've had to get it replaced under warranty probably about 7 times. Right now it works great, except for the Bluetooth. When my headphones are connected to both my phone and my laptop, the active audio always comes from my laptop which I always have the sound muted. It won't automatically play the sound that comes from my phone, which is frustrating. so it isn't detecting that sound is coming from my phone. I have to turn off Bluetooth on my laptop or disconnect from the Bose app every time."],
    },
    {
        "id": 6,
        "category": "over-ear",
        "name": "Audio-Technica ATH-M50xBT2",
        "price": 6990,
        "color": "black",
        "images": ["assets/over-ear/ath-m50xbt2/image-1.webp", "assets/over-ear/ath-m50xbt2/image-2.webp", "assets/over-ear/ath-m50xbt2/image-3.webp"],
        "features": ["bluetooth"],
        "description-title": "EXPECT MORE FROM YOUR WIRELESS.",
        "description-text": "The ATH-M50xBT2 is the second generation of our critically acclaimed M-Series wireless over-ear headphones. These headphones feature 45 mm large aperture drivers in a wireless design, so listeners will enjoy the same sonic signature of the  legendary ATH-M50x studio headphones. With this update, we’ve also introduced several noticeable enhancements, such as improved vocal pickup for better call quality, an updated USB-C connection, and multipoint pairing mode.",
        "overall-rating": 3.3,
        "rating": [5, 2, 5, 5],
        "reviewer": ["Bora8008", "Wakal", "Arturalex", "TNI Classmates"],
        "reviews": ["The sounds is amazing and they almost set themselves up, it really is almost as easy as taking them out of the box and turning them on to get them paired and working. I love the flexibility, comfort, volume, battery life, etc. Would absolutely recommend!",
            "Everything about the headphones are great EXCEPT for the construction. It has a very common issue of a flimsy plastic part within the hinge breaking causing the headphones to no longer sit flush with the head. I got this product a little under two years ago and it has broken the same way twice. I got it replaced under warranty, but I also had a pair of ATH M50-X that I got ten years ago that broke in exactly the same way. It has broken three times the same way. They are great headphones, but they will break on you, no question.",
            "Thats a very good phones!!! Amazing!!!",
            "This is one of Poom's favourite over-ear headphones! He wears it all the time to play video games! (The blue one though)."],
    },
    {
        "id": 7,
        "category": "over-ear",
        "name": "Sony MDR-XB950B1 Extra Bass",
        "price": 5990,
        "color": "black",
        "images": ["assets/over-ear/mdr-xb950B1/image-1.webp", "assets/over-ear/mdr-xb950B1/image-2.webp", "assets/over-ear/mdr-xb950B1/image-3.webp"],
        "features": ["bluetooth"],
        "description-title": "WIRELESS AND FREE.",
        "description-text": "Explore your favourite tracks in new depth with EXTRA BASS™, and listen over BLUETOOTH® wireless technology for up to 18 hours.",
        "overall-rating": 3.5,
        "rating": [5, 2, 5, 5],
        "reviewer": ["Basshead91", "Jlewis2345","MrMuche", "TNI Classmates"],
        "reviews": ["The build is solid and sturdy. The sound is phenomenal, with the built-in Electro Bass Booster works wonder to my bass-based ears (imma bass head for sure ). The BASS EFFECT button definitely brings the already-punchy bass to the next level. The skull-rattling bass is out of this world. In terms of durability, i hope it will last long, as the swivels scared me. Overall, 5 stars.",
            "The bad is the swivel always breaks!!!! I am on my second pair and they just broke taking them off my head:(",
            "I am so far very happy with the product even though this is a 2017 model it look better than the latest Sony headphones",
            "This is one of Sora's favourite over-ear headphones! He has been wearing it for more than 3 years now!"],
    },
    {
        "id": 8,
        "category": "over-ear",
        "name": "Soundcore Space One",
        "price": 2990,
        "color": "black",
        "images": ["assets/over-ear/space-one/image-1.webp", "assets/over-ear/space-one/image-2.webp", "assets/over-ear/space-one/image-3.webp"],
        "features": ["noise-cancelling", "bluetooth"],
        "description-title": "NOISE CANCELLING UP. CROWD NOISE DOWN.",
        "description-text": "Surrounded by noise, trying to relax while the sounds of bickering, crying babies, and mundane work calls invade your ears. Reclaim your personal ambience with Space One, engineered to excel in reducing 2X the crowd noise, especially voices.",
        "overall-rating": 4.5,
        "rating": [5, 2, 5],
        "reviewer": ["Christopher", "J.S.", "TNI Classmates"],
        "reviews": ["Great product, the sound is crisp, decent noise cancellation great price.",
            "With anc on I can still hear nearly everything, just a bit reduced. Normally I liked them but today they kept connecting to a different Bluetooth device than my own, with no way of stopping it. That was one of the most frustrating experiences I ever had.",
            "This is one of Daniel's favourite over-ear headphones! He just loves wearing it!"],
    },
    {
        "id": 9,
        "category": "over-ear",
        "name": "Sennheiser Momentum 4",
        "price": 12990,
        "color": "ivory",
        "images": ["assets/over-ear/momentun-4/image-1.webp", "assets/over-ear/momentun-4/image-2.webp", "assets/over-ear/momentun-4/image-3.webp"],
        "features": ["noise-cancelling", "ambient-sound", "bluetooth"],
        "description-title": "GOOSEBUMPS GUARANTEED.",
        "description-text": "Discover best-in-class sound with our audiophile-inspired accoustic system. Enjoy your favorite music like never before with our audiophile-inspired 42mm transducer system that delivers brilliant dynamics, clarity and musicality. Make the sound perfect for you using the built-in EQ, presets, sound modes, and Sound Personalization feature, which tailors the audio to your individual hearing.",
        "overall-rating": 4.1,
        "rating": [5, 4, 5],
        "reviewer": ["Calleb", "Jabez", "TNI Classmates"],
        "reviews": ["In all these aspects these headphones excell! Build is a little less premium feeling due to plastic but it is a quality plastic wrapped in fabric (top) and rubber (bottom) for the headband and standard fake leather earpads but still very cozy and one thing to note is my ears do touch the driver's but it's not bad like other headphones. I can get through a gym session or walk but that's about the limit which is all I need. Lightweight build and durable. Touch controls are awesome! No issues with them as many do have apparently. I've worn these in the gym and long hot sweaty walks with no issues at all. Sound is really good. Eq is a little wonky and sound is a bit muddy for Sennheiser which is weird to me but with the personalized sound on the app transforms these into god tier. Overall these are good. I had the px7s2e from Bowers though and the sound is more crystal clear and speedy on those. That headphone is also heavier and more durable due to metal build.",
            "Awesome in Noise canceling and very light. Also good sounding headphone, Well balanced mix in sound frequency.",
            "This is one of Paris's favourite brand of headphones! I don't know why but she said she likes it"],
    },
    {
        "id": 10,
        "category": "over-ear",
        "name": "Logitech Pro X 2 Lightspeed",
        "price": 7790,
        "color": "black",
        "images": ["assets/over-ear/pro-x-2-lightspeed/image-1.webp", "assets/over-ear/pro-x-2-lightspeed/image-2.webp", "assets/over-ear/pro-x-2-lightspeed/image-3.webp"],
        "features": ["bluetooth"],
        "description-title": "DESIGNED WITH PROS.",
        "description-text": "Designed with pros. Engineered to win. PRO X 2 LIGHTSPEED headset features pro-grade sound, LIGHTSPEED wireless, and supreme comfort for the highest levels of competition. Hear every footstep, action, and pin pull with the immersive soundscape enabled by graphene drivers.",
        "overall-rating": 5,
        "rating": [5, 5, 5],
        "reviewer": ["Sean", "Jacob", "TNI Classmates"],
        "reviews": ["Wearing this headset makes me feel like I can hear again. I used to own Turtle Beach Stealth 600s and whenever I heard noises in game I could never decipher where the sounds were coming from. Now I can instantly recognize where sounds are in game. Will never buy a non Logitech headset ever again.",
            "I have purchased the pro x 2 lights peed as well as the G513 Carbon and silver and their wireless powerplay mouse mat for the g502 X Plus and as well as their Yeti Studio microphone, best products I have ever had and experienced in a long time, decided to go with a minimalistic look since I got so tired of razer, I recommend all of these products,Read more about review stating Best products ever incredible build quality as well as suitable for my streaming needs, Logitech forever.",
            "This is one of Winner's favourite on-ear headphones! He wears it all the time whenever he plays videogames!"],
    },
    // ------------------------------------------------------------------------------------------------------------------------ //
    {
        "id": 20,
        "category": "on-ear",
        "name": "Skullcandy Riff Wireless 2",
        "price": 1990,
        "color": "black",
        "images": ["assets/on-ear/riff-wireless-2/image-1.webp", "assets/on-ear/riff-wireless-2/image-2.webp", "assets/on-ear/riff-wireless-2/image-3.webp"],
        "features": ["bluetooth"],
        "description-title": "BOLD SOUND, UNPLUGGED.",
        "description-text": "On-ear headphones are all about all-day battery and comfort, and Riff 2 is no exception. It delivers the goods affordably with 34 hours of battery life, a backup aux cable and the peace of mind that comes with Tile™ finding technology.",
        "overall-rating": 4.7,
        "rating": [5, 4, 5],
        "reviewer": ["Trevor", "John", "Jade"],
        "reviews": ["Very comfortable with great sound,perfect for the gym.",
            "The sound is great for the price, would buy from Skullcandy again.",
            "Great sound quality, very comfortable to wear & great charge lasts long time!!"],
    },
    {
        "id": 21,
        "category": "on-ear",
        "name": "Marshall Major V",
        "price": 5990,
        "color": "ivory",
        "images": ["assets/on-ear/major-v/image-1.webp", "assets/on-ear/major-v/image-2.webp", "assets/on-ear/major-v/image-3.webp"],
        "features": ["noise-cancelling", "bluetooth"],
        "description-title": "MARSHALL SIGNATURE SOUND.",
        "description-text": "From the explosive Marshall signature sound to the everlasting design, every detail of these headphones has been painstakingly refined. Featuring 100+ hours of wireless playtime combined with a rugged and foldable design, Major V is best paired with your next great adventure.",
        "overall-rating": 4.8,
        "rating": [5, 3, 5],
        "reviewer": ["Julia", "Redrain", "TNI Classmates"],
        "reviews": ["I really love my new major v headphones. After I had some issues with my previous ones, I wrote a mail to the customer service and had the best support. So thank you very much, 10/10.",
            "Its a little bit uncomfortable on the ear.",
            "This is Un's favourite brand of headphones! She has a whole collection of Marshall!"],
    },
    {
        "id": 22,
        "category": "on-ear",
        "name": "Beats Solo 4",
        "price": 6990,
        "color": "black",
        "images": ["assets/on-ear/solo4/image-1.webp", "assets/on-ear/solo4/image-2.webp", "assets/on-ear/solo4/image-3.webp"],
        "features": ["bluetooth"],
        "description-title": "STANDS OUT. STAYS ON.",
        "description-text": "Personalized Spatial Audio with dynamic head tracking uses built-in gyroscopes and accelerometers to surround you with sound as you move, creating a truly immersive listening experience.",
        "overall-rating": 4.5,
        "rating": [5, 4, 5],
        "reviewer": ["Amy", "Johana", "Bethany"],
        "reviews": ["Super fast charge and holds charge a long time. Easy to use, noise cancelling for the most part. I use them at work and home. Am able to make/answer calls or listen to music. Sturdy case. 10:10",
            "These headphones are easy to use connecting fast to Bluetooth . The charging time is fast and the battery life is long .I enjoy the variety of color options available. The performance is great. The sound is clear and loud with a great bass. They are comfortable and durable. Great value for the money.",
            "Easy to run in, perfect for music, not good for chatting on the phone. It will pick up all noise around you."],
    },
    // ------------------------------------------------------------------------------------------------------------------------ //
    {
        "id": 30,
        "category": "in-ear",
        "name": "Beats Studio Buds+",
        "price": 5990,
        "color": "ivory",
        "images": ["assets/in-ear/studio-buds-plus/image-1.webp", "assets/in-ear/studio-buds-plus/image-2.webp", "assets/in-ear/studio-buds-plus/image-3.webp"],
        "features": ["noise-cancelling", "ambient-sound", "bluetooth"],
        "description-title": "POWERFUL SOUND. PERFECT FIT.",
        "description-text": "Beats Studio Buds + feature powerful, balanced sound, Active Noise Cancelling (ANC), and Transparency mode. Enjoy high-quality calls, enhanced Apple & Android compatibility, up to 36 hours of listening time with charging casefootnote2 and four ear tip options to ensure a comfortable all-day fit.",
        "overall-rating": 4.3,
        "rating": [5, 5, 4],
        "reviewer": ["Relsie", "Stephen", "Quyen"],
        "reviews": ["Still using the product after I bought it last year. Battery is still in good health.",
            "The noise cancellation feature on this is incredible!! With AirPods they die on my every year or two. These last a long time and I’d prefer working out with these in than AirPods due to the noise cancellation. I’m very happy with my purchase.",
            "These earbuds have worked well over time. They connect to my phone instantly when I open the case, which I like. The only reason I rated 4 stars is because if you work out with these, you will have them fall out of your ears at least once or twice throughout the workout. Overall, it is good quality."],
    },
    {
        "id": 31,
        "category": "in-ear",
        "name": "Skullcandy Rail ANC",
        "price": 4990,
        "color": "white",
        "images": ["assets/in-ear/rail-anc/image-1.webp", "assets/in-ear/rail-anc/image-2.webp", "assets/in-ear/rail-anc/image-3.webp"],
        "features": ["noise-cancelling", "ambient-sound", "bluetooth"],
        "description-title": "FEATURE-PACKED, NOISE CANCELING.",
        "description-text": "Enjoy big, bright sound with no distractions. Rail ANC combines all of our top tech with 4-mic digital active noise canceling for the ultimate on-the-go audio experience.",
        "overall-rating": 4.3,
        "rating": [4, 5, 5],
        "reviewer": ["Alexander", "Tobias", "Isac"],
        "reviews": ["Great Product! ANC could work a bit better in windy conditions, but other than that absolutely happy with the Rail earbuds!",
            "Subpar ANC. Out of the box, the ANC feels useless. The App is clunky and has loading times in places one woudönt wxpect. But th worst thing of all is that the Earbuds routinely FORGET their customised Button actions, no matter how often I reassgin them. Dont buy skullcandy.",
            "These earbuds are awesome; the sound is clear and powerful. The ANC is so-so, but for the price, it's what you get…"],
    },
    {
        "id": 32,
        "category": "in-ear",
        "name": "Skullcandy Rail",
        "price": 3990,
        "color": "black",
        "images": ["assets/in-ear/rail/image-1.webp", "assets/in-ear/rail/image-2.webp", "assets/in-ear/rail/image-3.webp"],
        "features": ["ambient-sound", "bluetooth"],
        "description-title": "FULLY LOADED ALL-DAY LISTENING.",
        "description-text": "We created Rail with a simple set of design requirements — it had to be the best-sounding, best-looking, most comfortable, most intelligent earbud ever made, Mission accomplished.",
        "overall-rating": 4.5,
        "rating": [5, 5, 4],
        "reviewer": ["Ian", "Eglis", "Lindsay"],
        "reviews": ["This product is of very good quality at a good price. I would recommend Skull Candy to anyone as there products and services are second to none.",
            "Really amazing headphones for the price. It has amazing bass for the size of the headphones as well as the noise canceling overall I'm very Impressed with the quality of these headphones especially for the low price compared to different brands.",
            "After buying Dime earbuds which turned out to be faulty I can only say the Rail earbuds are as good as I was originally expecting. I would recommend them as a good all round option."],
    },
    {
        "id": 33,
        "category": "in-ear",
        "name": "Grado GT220",
        "price": 12990,
        "color": "black",
        "images": ["assets/in-ear/gt220/image-1.webp", "assets/in-ear/gt220/image-2.webp", "assets/in-ear/gt220/image-3.webp"],
        "features": ["bluetooth"],
        "description-title": "LOOK MOM! NO WIRES.",
        "description-text": "Our first true wireless in-ears, the GT220 mark a milestone in our seven decades of audio. Years in the making, we didnt want to rush the process of creating a compact and versatile wireless Grado headphone with such vocality and depth. Control music, calls, and more with just a tap, or your voice with the built-in microphone. Easy to always have around, they are ready when you are.",
        "overall-rating": 4.6,
        "rating": [5, 5, 3],
        "reviewer": ["Nathane", "Brett", "Coop"],
        "reviews": ["Great sound. And good for working out and great call clarity.",
            "The GT220 earbuds have been an ear opener! After using some nice wired earphones for a long time, the Grado wireless speakers provided amazing high quality sound for an approachable price. Absolutely recommend.",
            "It sounds almost like a wired Grado! So that part's nice. Battery life is great. The case easily charges two weeks of listening time for me. I've been using these for a few months, hoping the interface issues were my fault, but the sensitivity of the earphones makes them risky to use. If anything touches them (hair follicles, sweat, hat, etc.) the volume may go up or down and lock-up without warning. - Hurts my ears!! - Yet my paws can't get the earphones to change volume when I actually want them to."],
    },
    {
        "id": 34,
        "category": "in-ear",
        "name": "Edifier NeoBuds Pro",
        "price": 1590,
        "color": "white",
        "images": ["assets/in-ear/neobuds-pro/image-1.webp", "assets/in-ear/neobuds-pro/image-2.webp", "assets/in-ear/neobuds-pro/image-3.webp"],
        "features": ["noise-cancelling", "bluetooth"],
        "description-title": "FEEL THE MUSIC AS IT IS.",
        "description-text": "The NeoBuds Pro are the first True Wireless Stereo earbuds to achieve Hi-Res Audio certification. Expertly tuned by our world-class acoustics team to deliver professional studio-grade sound, the NeoBuds Pro reach a frequency response of 40KHz, to perform extreme audio quality like no other in-ear device has ever done before.",
        "overall-rating": 3.9,
        "rating": [3, 5, 2, 5],
        "reviewer": ["Rayan", "Duskhero", "Manning", "TNI Classmates"],
        "reviews": ["The sound in these headphones is fantastic, clear and full of bass. I have purchased the Edifier S2000 home bookshelf speakers, absolutely love to listen to them. The headphones were the same in terms of sound quality, but after about 9 months the right ear bud stopped working. Customer service isn’t great and returns can only happen if you have 100% of the original packaging, which I did not have.",
            "Its amazing to have something this complete and well rounded for that price point. only negative for me was the phone app witch require you to have your GPS on to open it.",
            "I really enjoyed these headphones for the couple months that both headphones worked. The sound quality and noise cancellation were great. There were some rather annoying connectivity issues but was overall happy with the product. However, after only a few months the speaker went out on one of the earbuds (Handled these very carefully, not dropped, etc.). It was not a connectivity issue as there is a small speaker on the back that would still function but the main speaker on the front stopped working.",
            "This is one of Bank's favourite in-ear headphones! He just loves wearing it!"],
    },
    {
        "id": 35,
        "category": "in-ear",
        "name": "CMF Buds Pro 2",
        "price": 2399,
        "color": "black",
        "images": ["assets/in-ear/buds-pro-2/image-1.webp", "assets/in-ear/buds-pro-2/image-2.webp", "assets/in-ear/buds-pro-2/image-3.webp"],
        "features": ["noise-cancelling", "bluetooth"],
        "description-title": "DIAL UP THE SOUND.",
        "description-text": "Meet the industry's first customisable Smart Dial. Twist to adjust volume and manage playback. Press to control noise cancellation, activate the Voice Assistant, switch to Low Lag Mode or mute your microphone during meetings. Tailor your experience further by pre-setting functions in the Nothing X app.",
        "overall-rating": 4.5,
        "rating": [5, 5, 2, 5],
        "reviewer": ["Troy", "Rexy", "J. Brad", "TNI Classmates"],
        "reviews": ["I previously owned the JLAB wireless earhook earbuds and these CMF buds are much higher quality. The sound quality is very good, and the sensor controllers, such as pausing when you take the buds out of your ear and audio controls, even worked on my MP3 player! My only gripe is that the larger orange bulb heads take some getting used to in your ear, but for the level of noise cancellation, it is completely worth it.",
            "for a bass head like me, I love the extra bass setting. mids and highs are a bit lacking in clarity but was able to adjust source to boost it. no complaints for the price. Bluetooth connectivity is decent. battery is great. the wheel control is a nice touch.",
            "Things started to fall off on the other features unfortunately. First, the sound cancelling was literally non-existent. I used them like I do my bose quietcomfort earbuds while I mow the lawn. I could tell no difference in noise cancellation with the feature on or off and I struggled to hear music due to the lawn mower noise. Second, the microphone quality was poor enough that people on my conference calls were complaining. So, if you just want to listen to music without noise cancellation, I can highly recommend them. For noise cancellation or conference calls, look elsewhere.",
            "This is one of Sun's favourite in-ear headphones! He said he didn't buy it yet but knew in his heart that he will definately love it if he owns one!"],
    },
    {
        "id": 36,
        "category": "in-ear",
        "name": "Jabra Elite 8 Active",
        "price": 7690,
        "color": "black",
        "images": ["assets/in-ear/elite-8-active/image-1.webp", "assets/in-ear/elite-8-active/image-2.webp", "assets/in-ear/elite-8-active/image-3.webp"],
        "features": ["noise-cancelling", "ambient-sound", "bluetooth"],
        "description-title": "NOTHING TOUGHER.",
        "description-text": "The worlds toughest earbuds: dust, water, and sweatproof.",
        "overall-rating": 4.9,
        "rating": [5, 5, 5],
        "reviewer": ["Jake", "Amanda", "TNI Classmates"],
        "reviews": ["I think these are good and great sound. I was but concerned that they wouldn’t fit my small ears but they do and are very comfortable. And secure. The materials are good quality easy to grip and hold. The heat through mode and cancellation work so I need to be careful when out in public as they submerge you into the audio. The app is good as well easy to use. The sound options are great",
            "I needed some new earphones for the gym as my previous ones had broke. Thankfully I decided to give these a try. The Jabra Elite earphones are lot comfier than I expected and the sound is amazing! Having wore these at the gym on various machines I found the securely stay in the ear during my workout with no need to adjust. Which is a bonus. I love the app functionality which lets you customise them as you like offering impressive sound quality with a deep bass and noise cancellation. Overall these are easy to pair, have a great battery life, light weight and durable, while offering fantastic blend of performance, comfort, and style. Highly recommended.",
            "This is one of Peem's favourite brand of headphones! He just loves it!"],
    },
    {
        "id": 37,
        "category": "in-ear",
        "name": "Sony WF-1000XM5",
        "price": 10990,
        "color": "black",
        "images": ["assets/in-ear/wf-1000xm5/image-1.webp", "assets/in-ear/wf-1000xm5/image-2.webp", "assets/in-ear/wf-1000xm5/image-3.webp"],
        "features": ["noise-cancelling", "ambient-sound", "bluetooth"],
        "description-title": "THE BEST NOISE CANCELLING HEADPHONES.",
        "description-text": "The WF-1000XM5 feature cutting-edge technology to deliver premium sound quality and the best noise-cancelling performance on the market. Real-time audio processors and high-performance mics power the specially designed driver unit Dynamic Driver X, for wide frequency reproduction, deep bass and clear vocals. They are designed to immerse you in a sound so good, it feels like you’re in the studio with your favourite artists. The WF-1000XM5 headphones raise the bar for distraction-free listening and clarity.",
        "overall-rating": 4,
        "rating": [5, 3, 4],
        "reviewer": ["Ranesh", "Bill3600", "TNI Classmates"],
        "reviews": ["Great sound and clarity. Excellent noice cancelling too",
            "Sony spare part is hard to purchase. 1. Sony original Ear tips is no available in the market. 2. Earbuds battery replacement not available. 3. Earbuds charging case missing is hard to found replacement. 4. Driving mode not available.",
            "This is not one of my classmates' favourite but mine! While it is not my all-time favourite, I like to wear this for my everyday listening!"],
    },


];
export default products;